---
ID: "8627ff73-8ddd-464b-977b-af9665c5b9cb"
Parent: "7cf7f8e8-c74d-47ac-af9d-1c2df877bd8b"
Template: "7cf7f8e8-c74d-47ac-af9d-1c2df877bd8b"
Path: "/sitecore/templates/Project/ai-sales-agent/Page Content/Logo Carousel/Logo Category/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{E31AD73C-B7F4-492C-B812-8A18806A60F1}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "b5c6b71f-1344-4329-861f-353f7f2ba736"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260917T195739Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zainarshad@7kcdev.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zainarshad@7kcdev.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5472b656-eb11-450d-bc89-358f23090dec"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zainarshad@7kcdev.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260917T195804Z
