---
ID: "46fe6f35-1d99-4544-84e2-5a51ee34798d"
Parent: "32c3e360-17b4-4c1d-99a4-ce4f7fdfe1c7"
Template: "32c3e360-17b4-4c1d-99a4-ce4f7fdfe1c7"
Path: "/sitecore/templates/Project/ai-sales-agent/Page Content/Testimonial/Testimonial/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{9AF2AE0A-581B-41CC-A696-0C7C41E41823}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "ab4096a5-990e-41ad-b961-ded1d927ddd9"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260921T154422Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hammad@7kcdev.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hammad@7kcdev.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "69e64c47-635c-4d63-b9fe-d843047b9f2f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\hammad@7kcdev.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260921T154438Z
