---
ID: "2954d51a-2d5e-459e-a49a-c7cecfd50a5c"
Parent: "af68438b-41af-4531-a96f-f0566fde399e"
Template: "af68438b-41af-4531-a96f-f0566fde399e"
Path: "/sitecore/templates/Project/ai-sales-agent/Page Content/Pricing Section/Cards/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{7361361B-8B60-42A8-9734-D14D5925C077}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "87fd24e2-d6ab-475a-b28f-dfd4795ddb9e"
Languages:
- Language: "sv-SE"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260922T201144Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\zainarshad@7kcdev.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\zainarshad@7kcdev.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c080f5c2-e7b2-4437-9d1d-cf1fb2c39b2a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zainarshad@7kcdev.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260922T201205Z
